### ISSUE TITLE
Error: mailgun is not a function

### ISSUE THREAD

**Issue by hosseinnedaee** [santiq/bulletproof-nodejs#36]
I installed the app and run `npm run start` then got this error:
```
error:   🔥 Error on dependency injector loader: { TypeError: mailgun is not a function
    at Object.exports.default (/var/www/html/bulletproof-nodejs/src/loaders/dependencyInjector.ts:17:34)
    at Object.exports.default (/var/www/html/bulletproof-nodejs/src/loaders/index.ts:28:52)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  [stack]:
   'TypeError: mailgun is not a function\n    at Object.exports.default (/var/www/html/bulletproof-nodejs/src/loaders/dependencyInjector.ts:17:34)\n    at Object.exports.default (/var/www/html/bulletproof-nodejs/src/loaders/index.ts:28:52)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
  [message]: 'mailgun is not a function' }
(node:21788) UnhandledPromiseRejectionWarning: TypeError: mailgun is not a function
    at Object.exports.default (/var/www/html/bulletproof-nodejs/src/loaders/dependencyInjector.ts:17:34)
    at Object.exports.default (/var/www/html/bulletproof-nodejs/src/loaders/index.ts:28:52)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:21788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21788) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

but after I made this change in  _dependencyInjector.js_ file, the error fixed:
`import * as mailgun from 'mailgun-js';` to `import mailgun from 'mailgun-js';`

If you agree with this solution I can submit a PR.

but I why this error just show for me?!

**Comment by santiq** [comment]
Hi @hosseinnedaee ! 

Thanks for noticing this error. It seems to be related to #26 

Please submit a PR :)

**Comment by hosseinnedaee** [comment]
You're welcome @santiq
I submitted a PR #37
