### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by firecrackerz** [santiq/bulletproof-nodejs#9]
```shell
Error: write EPIPE
    at WriteWrap.afterWrite (net.js:868:14)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by santiq** [comment]
Can you provide more context?

**Comment by firecrackerz** [comment]
After sometime nodemon crashes for no reason
```bash
 DB loaded and connected!
 Agenda injected into container
Dependency Injector loaded
Jobs loaded
Express loaded
 Kendrick Server listening on port:  3000
 Agenda index ensured
(node:7196) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Error: write EPIPE
    at WriteWrap.afterWrite (net.js:868:14)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by santiq** [comment]
I tested if after some time it crashed for no reason and it didn't so I can't help you :/
